server:
  enable: True
  port: 9002
  loglevel: "info"

safe_song_load: False
always_vip: True
enabled_gates:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
